package tp_JDBC;

import java.awt.image.RescaleOp;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

public class DAOEtudiant {
	private static DAOEtudiant instance = null;
	private Connection connection = null;

	private DAOEtudiant() throws SQLException {
		connection = ConnexionUnique.getInstance().getConnection();
	}

	public static DAOEtudiant getInstance() throws SQLException {
		if (instance == null) {
			instance = new DAOEtudiant();
		}
		return instance;
	}

	private void checkIfEtudiantNotInExistingAssociation(Etudiant etu) {
		// TODO
		// throw exeption if etudiant in existing association
	}

	// USELESS (spec misunderstood) but might be useful for another project
//	private int getMaxId() throws SQLException {
//		String query = "SELECT MAX(NUM_ET) as MAX_NUM_ET FROM ETUDIANT";
//		Statement statement = connection.createStatement();
//		ResultSet queryResults = statement.executeQuery(query);
//		queryResults.next(); // move to first position of ResultSet
//		int maxID = queryResults.getInt("MAX_NUM_ET");
//		return maxID;
//	}

	private int getAutoGeneratedNumEt(Statement statement) throws SQLException {
		ResultSet generatedKeys = statement.getGeneratedKeys();

		if (generatedKeys.next()) { // if ResultSet is not empty
			int key = generatedKeys.getInt(1);
			return key;
		} else {
			throw new SQLException(
					"Error when inserting etudiant: not auto-generated key retrived");
		}

	}

	public Etudiant insert(Etudiant etu) throws SQLException {
		this.checkIfEtudiantNotInExistingAssociation(etu);
		Statement statement = connection.createStatement();
		String query = "INSERT INTO ETUDIANT(NOM_ET, PRENOM_ET, CP_ET, VILLE_ET, ANNEE, GROUPE) "
				+ "VALUES ('"
				+ etu.getNomEt()
				+ "', '"
				+ etu.getPrenomEt()
				+ "', '"
				+ etu.getCpEt()
				+ "', '"
				+ etu.getVilleEt()
				+ "', '"
				+ etu.getAnnee() + "', '" + etu.getGroupe() + "');";
		int affectedRows = statement.executeUpdate(query,
				Statement.RETURN_GENERATED_KEYS);
		if (affectedRows != 1)
			throw new SQLException(
					"Error when inserting etudiant: affected rows != 1");

		int key = getAutoGeneratedNumEt(statement);

		etu.setNumEt(key);
		return etu;
	}
}
